blueprint:
  name: Random Light Color
  description: Sets given lights to a random color
  domain: script
  source_url: https://github.com/home-assistant/core/blob/dev/homeassistant/components/script/blueprints/random_color.yaml
  input:
    colors:
      name: Colors
      description: A list of color names to pick random from
      default:
        - "homeassistant"
        - "deeppink"
        - "chocolate"
        - "crimson"
        - "cyan"
        - "firebrick"
        - "floralwhite"
        - "forestgreen"
        - "fuchsia"
        - "green"
        - "hotpink"
        - "indigo"
        - "lavender"
        - "lime"
        - "magenta"
        - "maroon"
        - "midnightblue"
        - "mistyrose"
        - "olive"
        - "orange"
        - "orchid"
        - "purple"
        - "red"
        - "seashell"
        - "sienna"
        - "tan"
        - "teal"
        - "tomato"
        - "turquoise"
        - "violet"
        - "wheat"
        - "white"
        - "yellow"
      selector:
        object:

variables:
  fallback_colors:
    - "homeassistant"
    - "deeppink"
    - "chocolate"
    - "crimson"
    - "cyan"
    - "firebrick"
    - "floralwhite"
    - "forestgreen"
    - "fuchsia"
    - "green"
    - "hotpink"
    - "indigo"
    - "lavender"
    - "lime"
    - "magenta"
    - "maroon"
    - "midnightblue"
    - "mistyrose"
    - "olive"
    - "orange"
    - "orchid"
    - "purple"
    - "red"
    - "seashell"
    - "sienna"
    - "tan"
    - "teal"
    - "tomato"
    - "turquoise"
    - "violet"
    - "wheat"
    - "white"
    - "yellow"
  default_colors: !input colors
  colors: >
    {{ default_colors | default(fallback_colors) }}

fields:
  target:
    name: Light(s)
    description: The lights to give a random color
    required: true
    selector:
      target:
        entity:
          domain: light

sequence:
  - service: light.turn_on
    target: >
      {{ target }}
    data:
      color_name: >
        {{ colors | random }}
